//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankingApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class FD
    {
        public int SNO { get; set; }
        public Nullable<decimal> AccountNo { get; set; }
        public string Mode { get; set; }
        public string Rupees { get; set; }
        public Nullable<int> Period { get; set; }
        public Nullable<decimal> InterestRate { get; set; }
        public Nullable<System.DateTime> MaturityDate { get; set; }
        public Nullable<decimal> MaturityAmount { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
    }
}
