//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankingApplication
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BankingApplicationEntities : DbContext
    {
        public BankingApplicationEntities()
            : base("name=BankingApplicationEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminTable> AdminTable { get; set; }
        public virtual DbSet<UserTable> UserTable { get; set; }
        public virtual DbSet<UserAccount> UserAccount { get; set; }
        public virtual DbSet<Deposit> Deposit { get; set; }
        public virtual DbSet<Transfer> Transfer { get; set; }
        public virtual DbSet<Debit> Debit { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<FD> FD { get; set; }
    }
}
