//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankingApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transfer
    {
        public int SNO { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<decimal> AccountNo { get; set; }
        public string Name { get; set; }
        public Nullable<decimal> Balance { get; set; }
        public Nullable<decimal> ToTransfer { get; set; }
    }
}
