//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BankingApplication
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserAccount
    {
        public decimal Account_No { get; set; }
        public string Name { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public string PhoneNumber { get; set; }
        public string Address { get; set; }
        public string District { get; set; }
        public string State { get; set; }
        public byte[] Picture { get; set; }
        public string Gender { get; set; }
        public string MaritialStatus { get; set; }
        public string MotherName { get; set; }
        public string FatherName { get; set; }
        public Nullable<decimal> balance { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
    }
}
